### ISSUE TITLE
Consider implementing PartialEq, Eq, PartialOrd and Ord for Verbosity

### ISSUE THREAD

**Issue by mahor1221** [clap-rs/clap-verbosity-flag#107]
I'm using these implementations personally:

```rust
#[derive(Debug, Clone, Default)]
pub struct Verbosity<L: LogLevel>(clap_verbosity_flag::Verbosity<L>);

impl<L: LogLevel> Eq for Verbosity<L> {}
impl<L: LogLevel> PartialEq for Verbosity<L> {
    fn eq(&self, other: &Self) -> bool {
        self.0.log_level() == other.0.log_level()
    }
}

impl<L: LogLevel> Ord for Verbosity<L> {
    fn cmp(&self, other: &Self) -> Ordering {
        self.0.log_level().cmp(&other.0.log_level())
    }
}
impl<L: LogLevel> PartialOrd for Verbosity<L> {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}
```

**Comment by epage** [comment]
Whats the use case for these impls?  I'm a bit mixed about which way to implement this (effective or literal args) while it seems like this should be rare and implementable by users.

**Comment by mahor1221** [comment]
> Whats the use case for these impls?

I'm using them in unit tests to enforce an equality between config files and default values.    

>  I'm a bit mixed about which way to implement this (effective or literal args) while it seems like this should be rare and implementable by users.

I didn't know that. I think my use-case is rare and using the new type pattern is a better approach.
