### ISSUE TITLE
Not clear how to customise help menu

### ISSUE THREAD

**Issue by mbhall88** [clap-rs/clap-verbosity-flag#109]
Maybe I am being thick, but it isn't really clear how to customise the help menus.

I know it says in the documentation to implement `LogLevel`, but what am I supposed to implement it on? 

Maybe an example in the examples directory could be useful for others like me who want to alter the help menu but can't figure it out.

**Comment by epage** [comment]
The trait includes methods that are defaulted for you that you can provide on your own, like [`LogLevel::verbose_help`](https://docs.rs/clap-verbosity-flag/latest/clap_verbosity_flag/trait.LogLevel.html#method.verbose_help) which maps to `#[arg(help)]`.

**Comment by mbhall88** [comment]
Yeah I understand that, I just mean what do I need to implement `LogLevel` on? Because I obviously can't implement it on the clap-verbosity-flag `Level`. So I guess I need to create my own?
