### ISSUE TITLE
Disable for subcommands

### ISSUE THREAD

**Issue by ofek** [clap-rs/clap-verbosity-flag#45]
Is it possible with `flatten` to disable for subcommands?

**Comment by epage** [comment]
Not wanting the logging flags to be `global` or not wanting it to be `global` for specific subcommands?

And what is your application's use case that making them global doesn't work?

**Comment by ofek** [comment]
Part of https://github.com/clap-rs/clap/issues/4428#issuecomment-1295071158

I want to do `app run external cmd -v` rather than `app run -- external cmd -v`

**Comment by ofek** [comment]
My use case is solved https://github.com/clap-rs/clap/issues/4428#issuecomment-1295152104
