### ISSUE TITLE
Need to depend on the `log` crate to manually compare `LevelFilter`

### ISSUE THREAD

**Issue by Zykino** [clap-rs/clap-verbosity-flag#54]
To make the sample code I wrote in #53 work, we need to depend on the log crate.
Fixed sample code:
```rs
use log; // Need this and adding the dependency in Cargo.toml

fn foo() {
    if opt.verbose.log_level_filter() <= LevelFilter::Warn {
        eprintln!("Hide command's stdout");
    }

    if opt.verbose.log_level_filter() <= LevelFilter::Error {
        eprintln!("Hide command's stderr");
    }
}
```

I’m not sure if I want to use the log crate or tracing yet… Since this crate can support both logging frameworks, it feels strange to be forced to depends on the log crate to manually manage the log level.

I think the `LevelFilter` could be re-exported (and maybe `Level` too).

**Comment by matthiasbeyer** [comment]
Hey, thanks for your report!

So if we'd re-export `LevelFilter`, you would still depend on `log`, just not directly but transitively!

What I would rather imagine is that we define our own `LevelFilter` and provide `From<LevelFilter> for log::LevelFilter` and `From<LevelFilter> for tracing::level_filters::LevelFilter` behind feature gates.

What do you think?

**Comment by Zykino** [comment]
Sure, I proposed a "simple" re-export but having an internal representation sounds better. "Worst" cases scenario the raw verbosity value like proposed in #53. "Worst" in the sense that it take the familiar C approach instead of using a higher level data type.

**Comment by adriandelgado** [comment]
+1 to the feature gates idea

**Comment by matthiasbeyer** [comment]
Thanks Ed.
I would have done it myself but I am currently on vacation! 😂 Greetings from Crete!
